import { useCallback, useEffect, useMemo, useState } from 'react';
import { useNavigate } from '@tanstack/react-router';
import { AlertCircle, ArrowRight, BarChart3, Boxes, CheckCircle2, Clock3, DollarSign, RefreshCw, Wallet } from 'lucide-react';
import { financeSvc } from '@repo/axios-config';
import AdamsonBudgetLayout from '../layouts/Screenlayout';

type Scope={id:string;type:'role'|'unit';key:string;kind?:'Department'|'Section';label:string};
type DashboardData={scopes:Scope[];schoolYears:string[];currentYear:string|null;scope:Scope;year:string|null;counts:Record<string,number>;financial:Record<string,number>;statusDistribution:{label:string;value:number}[];queue:{id:number;requisition_no:string;unit:string;status:string|null;location:string|null;amount:number;date:string|null}[]};
type LinkTo='/transactions/requisition-process'|'/admin/budget-review'|'/admin/budget-adjustment-entry'|'/transactions/liquidation-submission'|'/admin/office-supplies'|'/transactions/budget-request-entry'|'/transactions/budget-proposal-entry';
const STORAGE_KEY='abms-dashboard-scope';
const peso=(n:number)=>new Intl.NumberFormat('en-PH',{style:'currency',currency:'PHP',minimumFractionDigits:2}).format(Number(n)||0);
const num=(n:number)=>new Intl.NumberFormat('en-US').format(Number(n)||0);

const roleConfig:Record<string,{subtitle:string;cards:[string,string,'count'|'money'][];links:[string,LinkTo][]}>={
  'logistics-access':{subtitle:'Pricing, purchasing, and fulfillment workload',cards:[['Awaiting Logistics','work_queue','count'],['Served','served','count'],['Processed RS','processed','count'],['Total RS','total_rs','count']],links:[['Open pricing & purchase queue','/transactions/requisition-process']]},
  'budget-access':{subtitle:'Budget review, utilization, adjustments, and liquidation',cards:[['Awaiting Budget','work_queue','count'],['Approved Budget','approved','money'],['Remaining Balance','balance','money'],['For Liquidation','liquidation','count']],links:[['Review requisitions','/transactions/requisition-process'],['Open Budget Review','/admin/budget-review'],['Budget adjustments','/admin/budget-adjustment-entry'],['Liquidation queue','/transactions/liquidation-submission']]},
  'admin-access':{subtitle:'Approvals, routing decisions, and workflow bottlenecks',cards:[['Awaiting Action','work_queue','count'],['Pending Amount','work_amount','money'],['Disapproved / Cancelled','cancelled','count'],['Total RS','total_rs','count']],links:[['Open administration queue','/transactions/requisition-process'],['Open Budget Review','/admin/budget-review']]},
  'controller-access':{subtitle:'Controller review decisions and requisition oversight',cards:[['Pending Controller Review','controller_pending','count'],['Controller Approved','controller_approved','count'],['Controller Disapproved','controller_disapproved','count'],['Total RS','total_rs','count']],links:[['Open Controller queue','/transactions/requisition-process']]},
  'stockroom-access':{subtitle:'Stockroom processing and served request activity',cards:[['To Process','work_queue','count'],['Served','served','count'],['Returned / Unserved','unserved','count'],['Total RS','total_rs','count']],links:[['Process requisitions','/transactions/requisition-process'],['Office supplies','/admin/office-supplies']]},
  department:{subtitle:'Department budget position and requisition activity',cards:[['Approved Budget','approved','money'],['Released / Used','released','money'],['Remaining Balance','balance','money'],['Pending RS','work_queue','count']],links:[['Create / view budget request','/transactions/budget-request-entry'],['Budget proposal','/transactions/budget-proposal-entry'],['Liquidation submission','/transactions/liquidation-submission']]},
};

export default function Home(){
  const navigate=useNavigate(); const [data,setData]=useState<DashboardData|null>(null); const [scope,setScope]=useState(localStorage.getItem(STORAGE_KEY)??''); const [year,setYear]=useState(''); const [loading,setLoading]=useState(true); const [error,setError]=useState('');
  const load=useCallback(async(nextScope:string,nextYear:string)=>{setLoading(true);setError('');try{const {data:res}=await financeSvc.get('/abms/dashboard',{params:{...(nextScope?{scope:nextScope}:{}),...(nextYear?{school_year:nextYear}:{})}});setData(res);setScope(res.scope.id);setYear(res.year??'');localStorage.setItem(STORAGE_KEY,res.scope.id);}catch(error:unknown){const err=error as {response?:{status?:number;data?:{message?:string}}};if(err.response?.status===403&&nextScope){localStorage.removeItem(STORAGE_KEY);setScope('');return load('',nextYear);}setData(null);setError(err.response?.data?.message??'Dashboard data could not be loaded.');}finally{setLoading(false);}},[]);
  useEffect(()=>{void load(localStorage.getItem(STORAGE_KEY)??'','');},[load]);
  const config=useMemo(()=>data?(data.scope.type==='role'?roleConfig[data.scope.key]:roleConfig.department):null,[data]);
  const value=(key:string,type:'count'|'money')=>type==='money'?peso(data?.financial[key]??0):num(data?.counts[key]??0);
  return <AdamsonBudgetLayout><div className="space-y-5 text-slate-900 dark:text-slate-100">
    <div className="flex flex-col gap-3 lg:flex-row lg:items-end lg:justify-between"><div><h1 className="text-xl font-bold">{data?.scope.label??'Dashboard'}</h1><p className="mt-1 text-xs uppercase tracking-widest text-slate-500">{config?.subtitle??'Your authorized ABMS overview'}</p></div><div className="flex flex-wrap gap-2">
      <select aria-label="Dashboard scope" value={scope} onChange={e=>{setScope(e.target.value);void load(e.target.value,year)}} className="rounded-lg border border-slate-300 bg-white px-3 py-2 text-xs font-semibold dark:border-slate-700 dark:bg-slate-900">{data?.scopes.map(s=><option key={s.id} value={s.id}>{s.label}</option>)}</select>
      <select aria-label="School year" value={year} onChange={e=>{setYear(e.target.value);void load(scope,e.target.value)}} className="rounded-lg border border-slate-300 bg-white px-3 py-2 text-xs font-semibold dark:border-slate-700 dark:bg-slate-900">{data?.schoolYears.map(y=><option key={y}>{y}</option>)}</select>
      <button onClick={()=>void load(scope,year)} className="rounded-lg border border-slate-300 p-2 dark:border-slate-700" aria-label="Refresh dashboard"><RefreshCw className={`h-4 w-4 ${loading?'animate-spin':''}`}/></button>
    </div></div>
    {error?<div className="rounded-xl border border-red-300 bg-red-50 p-8 text-center text-sm text-red-700 dark:border-red-900 dark:bg-red-950/30"><AlertCircle className="mx-auto mb-2 h-6 w-6"/>{error}<button onClick={()=>void load(scope,year)} className="ml-3 underline">Retry</button></div>:loading&&!data?<div className="py-24 text-center text-sm text-slate-500">Loading dashboard…</div>:data&&config?<>
      <div className="grid grid-cols-1 gap-3 sm:grid-cols-2 xl:grid-cols-4">{config.cards.map(([label,key,type],i)=>{const Icon=[Clock3,Wallet,DollarSign,CheckCircle2][i];return <div key={label} className="rounded-xl border border-slate-200 bg-white p-5 dark:border-slate-800 dark:bg-slate-900"><div className="flex items-center justify-between text-xs font-semibold uppercase tracking-wider text-slate-500"><span>{label}</span><Icon className="h-4 w-4 text-blue-500"/></div><p className="mt-4 text-2xl font-bold">{value(key,type)}</p><p className="mt-1 text-[10px] uppercase tracking-wider text-slate-500">School year {data.year??'—'}</p></div>})}</div>
      <div className="grid gap-4 xl:grid-cols-3"><section className="rounded-xl border border-slate-200 bg-white p-5 dark:border-slate-800 dark:bg-slate-900"><h2 className="mb-4 flex items-center gap-2 text-sm font-bold"><BarChart3 className="h-4 w-4 text-blue-500"/>Status distribution</h2>{data.statusDistribution.length?<div className="space-y-3">{data.statusDistribution.slice(0,8).map(row=>{const pct=data.counts.total_rs?Math.round(row.value/data.counts.total_rs*100):0;return <div key={row.label}><div className="mb-1 flex justify-between text-xs"><span className="capitalize">{row.label}</span><b>{row.value}</b></div><div className="h-2 rounded bg-slate-100 dark:bg-slate-800"><div className="h-2 rounded bg-blue-500" style={{width:`${pct}%`}}/></div></div>})}</div>:<Empty text="No requisitions for this school year."/>}</section>
      <section className="xl:col-span-2 rounded-xl border border-slate-200 bg-white p-5 dark:border-slate-800 dark:bg-slate-900"><h2 className="mb-4 flex items-center gap-2 text-sm font-bold"><Boxes className="h-4 w-4 text-blue-500"/>Current work queue</h2>{data.queue.length?<div className="overflow-x-auto"><table className="w-full text-left text-xs"><thead className="text-slate-500"><tr><th className="pb-3">RS No.</th><th>Department / Section</th><th>Status</th><th className="text-right">Amount</th></tr></thead><tbody>{data.queue.map(row=><tr key={row.id} className="border-t border-slate-100 dark:border-slate-800"><td className="py-3 font-semibold">{row.requisition_no}</td><td>{row.unit}</td><td className="capitalize">{row.status??'—'}</td><td className="text-right">{peso(row.amount)}</td></tr>)}</tbody></table></div>:<Empty text="Nothing currently requires action in this scope."/>}</section></div>
      <section className="rounded-xl border border-slate-200 bg-white p-5 dark:border-slate-800 dark:bg-slate-900"><h2 className="mb-3 text-sm font-bold">Quick actions</h2><div className="flex flex-wrap gap-2">{config.links.map(([label,to])=><button key={label} onClick={()=>navigate({to})} className="flex items-center gap-2 rounded-lg bg-blue-600 px-4 py-2 text-xs font-bold text-white hover:bg-blue-700">{label}<ArrowRight className="h-3.5 w-3.5"/></button>)}</div></section>
    </>:null}
  </div></AdamsonBudgetLayout>;
}

function Empty({text}:{text:string}){return <div className="py-12 text-center text-xs text-slate-500">{text}</div>}
