/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as MaintenanceIndexRouteImport } from './routes/maintenance/index'
import { Route as ApplyIndexRouteImport } from './routes/apply/index'
import { Route as StaffQueueRouteImport } from './routes/staff.queue'
import { Route as MaintenanceReportsRouteImport } from './routes/maintenance/reports'
import { Route as MaintenanceAccessDebugRouteImport } from './routes/maintenance/access-debug'
import { Route as ApplicationsApplicationIdRouteImport } from './routes/applications.$applicationId'
import { Route as StaffApplicationsApplicationIdRouteImport } from './routes/staff.applications.$applicationId'
import { Route as ApplicationsApplicationIdHistoryRouteImport } from './routes/applications.$applicationId.history'
import { Route as StaffApplicationsApplicationIdHistoryRouteImport } from './routes/staff.applications.$applicationId.history'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const MaintenanceIndexRoute = MaintenanceIndexRouteImport.update({
  id: '/maintenance/',
  path: '/maintenance/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApplyIndexRoute = ApplyIndexRouteImport.update({
  id: '/apply/',
  path: '/apply/',
  getParentRoute: () => rootRouteImport,
} as any)
const StaffQueueRoute = StaffQueueRouteImport.update({
  id: '/staff/queue',
  path: '/staff/queue',
  getParentRoute: () => rootRouteImport,
} as any)
const MaintenanceReportsRoute = MaintenanceReportsRouteImport.update({
  id: '/maintenance/reports',
  path: '/maintenance/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const MaintenanceAccessDebugRoute = MaintenanceAccessDebugRouteImport.update({
  id: '/maintenance/access-debug',
  path: '/maintenance/access-debug',
  getParentRoute: () => rootRouteImport,
} as any)
const ApplicationsApplicationIdRoute =
  ApplicationsApplicationIdRouteImport.update({
    id: '/applications/$applicationId',
    path: '/applications/$applicationId',
    getParentRoute: () => rootRouteImport,
  } as any)
const StaffApplicationsApplicationIdRoute =
  StaffApplicationsApplicationIdRouteImport.update({
    id: '/staff/applications/$applicationId',
    path: '/staff/applications/$applicationId',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApplicationsApplicationIdHistoryRoute =
  ApplicationsApplicationIdHistoryRouteImport.update({
    id: '/history',
    path: '/history',
    getParentRoute: () => ApplicationsApplicationIdRoute,
  } as any)
const StaffApplicationsApplicationIdHistoryRoute =
  StaffApplicationsApplicationIdHistoryRouteImport.update({
    id: '/history',
    path: '/history',
    getParentRoute: () => StaffApplicationsApplicationIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/applications/$applicationId': typeof ApplicationsApplicationIdRouteWithChildren
  '/maintenance/access-debug': typeof MaintenanceAccessDebugRoute
  '/maintenance/reports': typeof MaintenanceReportsRoute
  '/staff/queue': typeof StaffQueueRoute
  '/apply/': typeof ApplyIndexRoute
  '/maintenance/': typeof MaintenanceIndexRoute
  '/applications/$applicationId/history': typeof ApplicationsApplicationIdHistoryRoute
  '/staff/applications/$applicationId': typeof StaffApplicationsApplicationIdRouteWithChildren
  '/staff/applications/$applicationId/history': typeof StaffApplicationsApplicationIdHistoryRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/applications/$applicationId': typeof ApplicationsApplicationIdRouteWithChildren
  '/maintenance/access-debug': typeof MaintenanceAccessDebugRoute
  '/maintenance/reports': typeof MaintenanceReportsRoute
  '/staff/queue': typeof StaffQueueRoute
  '/apply': typeof ApplyIndexRoute
  '/maintenance': typeof MaintenanceIndexRoute
  '/applications/$applicationId/history': typeof ApplicationsApplicationIdHistoryRoute
  '/staff/applications/$applicationId': typeof StaffApplicationsApplicationIdRouteWithChildren
  '/staff/applications/$applicationId/history': typeof StaffApplicationsApplicationIdHistoryRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/applications/$applicationId': typeof ApplicationsApplicationIdRouteWithChildren
  '/maintenance/access-debug': typeof MaintenanceAccessDebugRoute
  '/maintenance/reports': typeof MaintenanceReportsRoute
  '/staff/queue': typeof StaffQueueRoute
  '/apply/': typeof ApplyIndexRoute
  '/maintenance/': typeof MaintenanceIndexRoute
  '/applications/$applicationId/history': typeof ApplicationsApplicationIdHistoryRoute
  '/staff/applications/$applicationId': typeof StaffApplicationsApplicationIdRouteWithChildren
  '/staff/applications/$applicationId/history': typeof StaffApplicationsApplicationIdHistoryRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/applications/$applicationId'
    | '/maintenance/access-debug'
    | '/maintenance/reports'
    | '/staff/queue'
    | '/apply/'
    | '/maintenance/'
    | '/applications/$applicationId/history'
    | '/staff/applications/$applicationId'
    | '/staff/applications/$applicationId/history'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/applications/$applicationId'
    | '/maintenance/access-debug'
    | '/maintenance/reports'
    | '/staff/queue'
    | '/apply'
    | '/maintenance'
    | '/applications/$applicationId/history'
    | '/staff/applications/$applicationId'
    | '/staff/applications/$applicationId/history'
  id:
    | '__root__'
    | '/'
    | '/applications/$applicationId'
    | '/maintenance/access-debug'
    | '/maintenance/reports'
    | '/staff/queue'
    | '/apply/'
    | '/maintenance/'
    | '/applications/$applicationId/history'
    | '/staff/applications/$applicationId'
    | '/staff/applications/$applicationId/history'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApplicationsApplicationIdRoute: typeof ApplicationsApplicationIdRouteWithChildren
  MaintenanceAccessDebugRoute: typeof MaintenanceAccessDebugRoute
  MaintenanceReportsRoute: typeof MaintenanceReportsRoute
  StaffQueueRoute: typeof StaffQueueRoute
  ApplyIndexRoute: typeof ApplyIndexRoute
  MaintenanceIndexRoute: typeof MaintenanceIndexRoute
  StaffApplicationsApplicationIdRoute: typeof StaffApplicationsApplicationIdRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/maintenance/': {
      id: '/maintenance/'
      path: '/maintenance'
      fullPath: '/maintenance/'
      preLoaderRoute: typeof MaintenanceIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/apply/': {
      id: '/apply/'
      path: '/apply'
      fullPath: '/apply/'
      preLoaderRoute: typeof ApplyIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/staff/queue': {
      id: '/staff/queue'
      path: '/staff/queue'
      fullPath: '/staff/queue'
      preLoaderRoute: typeof StaffQueueRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/maintenance/reports': {
      id: '/maintenance/reports'
      path: '/maintenance/reports'
      fullPath: '/maintenance/reports'
      preLoaderRoute: typeof MaintenanceReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/maintenance/access-debug': {
      id: '/maintenance/access-debug'
      path: '/maintenance/access-debug'
      fullPath: '/maintenance/access-debug'
      preLoaderRoute: typeof MaintenanceAccessDebugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/applications/$applicationId': {
      id: '/applications/$applicationId'
      path: '/applications/$applicationId'
      fullPath: '/applications/$applicationId'
      preLoaderRoute: typeof ApplicationsApplicationIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/staff/applications/$applicationId': {
      id: '/staff/applications/$applicationId'
      path: '/staff/applications/$applicationId'
      fullPath: '/staff/applications/$applicationId'
      preLoaderRoute: typeof StaffApplicationsApplicationIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/applications/$applicationId/history': {
      id: '/applications/$applicationId/history'
      path: '/history'
      fullPath: '/applications/$applicationId/history'
      preLoaderRoute: typeof ApplicationsApplicationIdHistoryRouteImport
      parentRoute: typeof ApplicationsApplicationIdRoute
    }
    '/staff/applications/$applicationId/history': {
      id: '/staff/applications/$applicationId/history'
      path: '/history'
      fullPath: '/staff/applications/$applicationId/history'
      preLoaderRoute: typeof StaffApplicationsApplicationIdHistoryRouteImport
      parentRoute: typeof StaffApplicationsApplicationIdRoute
    }
  }
}

interface ApplicationsApplicationIdRouteChildren {
  ApplicationsApplicationIdHistoryRoute: typeof ApplicationsApplicationIdHistoryRoute
}

const ApplicationsApplicationIdRouteChildren: ApplicationsApplicationIdRouteChildren =
  {
    ApplicationsApplicationIdHistoryRoute:
      ApplicationsApplicationIdHistoryRoute,
  }

const ApplicationsApplicationIdRouteWithChildren =
  ApplicationsApplicationIdRoute._addFileChildren(
    ApplicationsApplicationIdRouteChildren,
  )

interface StaffApplicationsApplicationIdRouteChildren {
  StaffApplicationsApplicationIdHistoryRoute: typeof StaffApplicationsApplicationIdHistoryRoute
}

const StaffApplicationsApplicationIdRouteChildren: StaffApplicationsApplicationIdRouteChildren =
  {
    StaffApplicationsApplicationIdHistoryRoute:
      StaffApplicationsApplicationIdHistoryRoute,
  }

const StaffApplicationsApplicationIdRouteWithChildren =
  StaffApplicationsApplicationIdRoute._addFileChildren(
    StaffApplicationsApplicationIdRouteChildren,
  )

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApplicationsApplicationIdRoute: ApplicationsApplicationIdRouteWithChildren,
  MaintenanceAccessDebugRoute: MaintenanceAccessDebugRoute,
  MaintenanceReportsRoute: MaintenanceReportsRoute,
  StaffQueueRoute: StaffQueueRoute,
  ApplyIndexRoute: ApplyIndexRoute,
  MaintenanceIndexRoute: MaintenanceIndexRoute,
  StaffApplicationsApplicationIdRoute:
    StaffApplicationsApplicationIdRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
