/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as MaintenanceIndexRouteImport } from './routes/maintenance/index'
import { Route as ApplyIndexRouteImport } from './routes/apply/index'
import { Route as StaffQueueRouteImport } from './routes/staff.queue'
import { Route as ApplicationsApplicationIdRouteImport } from './routes/applications.$applicationId'
import { Route as StaffApplicationsApplicationIdRouteImport } from './routes/staff.applications.$applicationId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const MaintenanceIndexRoute = MaintenanceIndexRouteImport.update({
  id: '/maintenance/',
  path: '/maintenance/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApplyIndexRoute = ApplyIndexRouteImport.update({
  id: '/apply/',
  path: '/apply/',
  getParentRoute: () => rootRouteImport,
} as any)
const StaffQueueRoute = StaffQueueRouteImport.update({
  id: '/staff/queue',
  path: '/staff/queue',
  getParentRoute: () => rootRouteImport,
} as any)
const ApplicationsApplicationIdRoute =
  ApplicationsApplicationIdRouteImport.update({
    id: '/applications/$applicationId',
    path: '/applications/$applicationId',
    getParentRoute: () => rootRouteImport,
  } as any)
const StaffApplicationsApplicationIdRoute =
  StaffApplicationsApplicationIdRouteImport.update({
    id: '/staff/applications/$applicationId',
    path: '/staff/applications/$applicationId',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/applications/$applicationId': typeof ApplicationsApplicationIdRoute
  '/staff/queue': typeof StaffQueueRoute
  '/apply/': typeof ApplyIndexRoute
  '/maintenance/': typeof MaintenanceIndexRoute
  '/staff/applications/$applicationId': typeof StaffApplicationsApplicationIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/applications/$applicationId': typeof ApplicationsApplicationIdRoute
  '/staff/queue': typeof StaffQueueRoute
  '/apply': typeof ApplyIndexRoute
  '/maintenance': typeof MaintenanceIndexRoute
  '/staff/applications/$applicationId': typeof StaffApplicationsApplicationIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/applications/$applicationId': typeof ApplicationsApplicationIdRoute
  '/staff/queue': typeof StaffQueueRoute
  '/apply/': typeof ApplyIndexRoute
  '/maintenance/': typeof MaintenanceIndexRoute
  '/staff/applications/$applicationId': typeof StaffApplicationsApplicationIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/applications/$applicationId'
    | '/staff/queue'
    | '/apply/'
    | '/maintenance/'
    | '/staff/applications/$applicationId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/applications/$applicationId'
    | '/staff/queue'
    | '/apply'
    | '/maintenance'
    | '/staff/applications/$applicationId'
  id:
    | '__root__'
    | '/'
    | '/applications/$applicationId'
    | '/staff/queue'
    | '/apply/'
    | '/maintenance/'
    | '/staff/applications/$applicationId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApplicationsApplicationIdRoute: typeof ApplicationsApplicationIdRoute
  StaffQueueRoute: typeof StaffQueueRoute
  ApplyIndexRoute: typeof ApplyIndexRoute
  MaintenanceIndexRoute: typeof MaintenanceIndexRoute
  StaffApplicationsApplicationIdRoute: typeof StaffApplicationsApplicationIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/maintenance/': {
      id: '/maintenance/'
      path: '/maintenance'
      fullPath: '/maintenance/'
      preLoaderRoute: typeof MaintenanceIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/apply/': {
      id: '/apply/'
      path: '/apply'
      fullPath: '/apply/'
      preLoaderRoute: typeof ApplyIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/staff/queue': {
      id: '/staff/queue'
      path: '/staff/queue'
      fullPath: '/staff/queue'
      preLoaderRoute: typeof StaffQueueRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/applications/$applicationId': {
      id: '/applications/$applicationId'
      path: '/applications/$applicationId'
      fullPath: '/applications/$applicationId'
      preLoaderRoute: typeof ApplicationsApplicationIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/staff/applications/$applicationId': {
      id: '/staff/applications/$applicationId'
      path: '/staff/applications/$applicationId'
      fullPath: '/staff/applications/$applicationId'
      preLoaderRoute: typeof StaffApplicationsApplicationIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApplicationsApplicationIdRoute: ApplicationsApplicationIdRoute,
  StaffQueueRoute: StaffQueueRoute,
  ApplyIndexRoute: ApplyIndexRoute,
  MaintenanceIndexRoute: MaintenanceIndexRoute,
  StaffApplicationsApplicationIdRoute: StaffApplicationsApplicationIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
