export const abmsTheme = {
  canvas: 'var(--abms-canvas)',
  canvasDeep: 'var(--abms-canvas-deep)',
  surface: 'var(--abms-surface)',
  surfaceSubtle: 'var(--abms-surface-subtle)',
  surfaceRaised: 'var(--abms-surface-raised)',
  surfaceOverlay: 'var(--abms-surface-overlay)',
  text: 'var(--abms-text)',
  textSoft: 'var(--abms-text-soft)',
  textMuted: 'var(--abms-text-muted)',
  textOnAccent: 'var(--abms-text-on-accent)',
  primary: 'var(--abms-primary)',
  primaryStrong: 'var(--abms-primary-strong)',
  primarySoft: 'var(--abms-primary-soft)',
  accent: 'var(--abms-accent)',
  accentStrong: 'var(--abms-accent-strong)',
  accentSoft: 'var(--abms-accent-soft)',
  success: 'var(--abms-success)',
  successSoft: 'var(--abms-success-soft)',
  warning: 'var(--abms-warning)',
  warningSoft: 'var(--abms-warning-soft)',
  danger: 'var(--abms-danger)',
  dangerSoft: 'var(--abms-danger-soft)',
  info: 'var(--abms-info)',
  infoSoft: 'var(--abms-info-soft)',
  border: 'var(--abms-border)',
  borderStrong: 'var(--abms-border-strong)',
  focus: 'var(--abms-focus)',
  grid: 'var(--abms-grid)',
  shadowSm: 'var(--abms-shadow-sm)',
  shadowMd: 'var(--abms-shadow-md)',
  shadowLg: 'var(--abms-shadow-lg)',
} as const;

export type AbmsThemeTokens = typeof abmsTheme;
