/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TestRouteImport } from './routes/test'
import { Route as GuidelinesRouteImport } from './routes/guidelines'
import { Route as AboutRouteImport } from './routes/about'
import { Route as MyLeaveRouteRouteImport } from './routes/my-leave/route'
import { Route as HrApprovalRouteRouteImport } from './routes/hr-approval/route'
import { Route as ForApprovalRouteRouteImport } from './routes/for-approval/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as MyLeaveIndexRouteImport } from './routes/my-leave/index'
import { Route as HrApprovalIndexRouteImport } from './routes/hr-approval/index'
import { Route as ForApprovalIndexRouteImport } from './routes/for-approval/index'
import { Route as ReportsFiledLeaveRouteImport } from './routes/reports/filed-leave'
import { Route as HrApprovalViewHrApprovalSheetRouteImport } from './routes/hr-approval/view-hr-approval-sheet'
import { Route as MyLeaveViewLeaveLeaveIdRouteImport } from './routes/my-leave/view-leave.$leaveId'
import { Route as MyLeaveLeaveFormChar123LeaveIdChar125RouteImport } from './routes/my-leave/leave-form.{-$leaveId}'

const TestRoute = TestRouteImport.update({
  id: '/test',
  path: '/test',
  getParentRoute: () => rootRouteImport,
} as any)
const GuidelinesRoute = GuidelinesRouteImport.update({
  id: '/guidelines',
  path: '/guidelines',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const MyLeaveRouteRoute = MyLeaveRouteRouteImport.update({
  id: '/my-leave',
  path: '/my-leave',
  getParentRoute: () => rootRouteImport,
} as any)
const HrApprovalRouteRoute = HrApprovalRouteRouteImport.update({
  id: '/hr-approval',
  path: '/hr-approval',
  getParentRoute: () => rootRouteImport,
} as any)
const ForApprovalRouteRoute = ForApprovalRouteRouteImport.update({
  id: '/for-approval',
  path: '/for-approval',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const MyLeaveIndexRoute = MyLeaveIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => MyLeaveRouteRoute,
} as any)
const HrApprovalIndexRoute = HrApprovalIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => HrApprovalRouteRoute,
} as any)
const ForApprovalIndexRoute = ForApprovalIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ForApprovalRouteRoute,
} as any)
const ReportsFiledLeaveRoute = ReportsFiledLeaveRouteImport.update({
  id: '/reports/filed-leave',
  path: '/reports/filed-leave',
  getParentRoute: () => rootRouteImport,
} as any)
const HrApprovalViewHrApprovalSheetRoute =
  HrApprovalViewHrApprovalSheetRouteImport.update({
    id: '/view-hr-approval-sheet',
    path: '/view-hr-approval-sheet',
    getParentRoute: () => HrApprovalRouteRoute,
  } as any)
const MyLeaveViewLeaveLeaveIdRoute = MyLeaveViewLeaveLeaveIdRouteImport.update({
  id: '/view-leave/$leaveId',
  path: '/view-leave/$leaveId',
  getParentRoute: () => MyLeaveRouteRoute,
} as any)
const MyLeaveLeaveFormChar123LeaveIdChar125Route =
  MyLeaveLeaveFormChar123LeaveIdChar125RouteImport.update({
    id: '/leave-form/{-$leaveId}',
    path: '/leave-form/{-$leaveId}',
    getParentRoute: () => MyLeaveRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/for-approval': typeof ForApprovalRouteRouteWithChildren
  '/hr-approval': typeof HrApprovalRouteRouteWithChildren
  '/my-leave': typeof MyLeaveRouteRouteWithChildren
  '/about': typeof AboutRoute
  '/guidelines': typeof GuidelinesRoute
  '/test': typeof TestRoute
  '/hr-approval/view-hr-approval-sheet': typeof HrApprovalViewHrApprovalSheetRoute
  '/reports/filed-leave': typeof ReportsFiledLeaveRoute
  '/for-approval/': typeof ForApprovalIndexRoute
  '/hr-approval/': typeof HrApprovalIndexRoute
  '/my-leave/': typeof MyLeaveIndexRoute
  '/my-leave/leave-form/{-$leaveId}': typeof MyLeaveLeaveFormChar123LeaveIdChar125Route
  '/my-leave/view-leave/$leaveId': typeof MyLeaveViewLeaveLeaveIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/guidelines': typeof GuidelinesRoute
  '/test': typeof TestRoute
  '/hr-approval/view-hr-approval-sheet': typeof HrApprovalViewHrApprovalSheetRoute
  '/reports/filed-leave': typeof ReportsFiledLeaveRoute
  '/for-approval': typeof ForApprovalIndexRoute
  '/hr-approval': typeof HrApprovalIndexRoute
  '/my-leave': typeof MyLeaveIndexRoute
  '/my-leave/leave-form/{-$leaveId}': typeof MyLeaveLeaveFormChar123LeaveIdChar125Route
  '/my-leave/view-leave/$leaveId': typeof MyLeaveViewLeaveLeaveIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/for-approval': typeof ForApprovalRouteRouteWithChildren
  '/hr-approval': typeof HrApprovalRouteRouteWithChildren
  '/my-leave': typeof MyLeaveRouteRouteWithChildren
  '/about': typeof AboutRoute
  '/guidelines': typeof GuidelinesRoute
  '/test': typeof TestRoute
  '/hr-approval/view-hr-approval-sheet': typeof HrApprovalViewHrApprovalSheetRoute
  '/reports/filed-leave': typeof ReportsFiledLeaveRoute
  '/for-approval/': typeof ForApprovalIndexRoute
  '/hr-approval/': typeof HrApprovalIndexRoute
  '/my-leave/': typeof MyLeaveIndexRoute
  '/my-leave/leave-form/{-$leaveId}': typeof MyLeaveLeaveFormChar123LeaveIdChar125Route
  '/my-leave/view-leave/$leaveId': typeof MyLeaveViewLeaveLeaveIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/for-approval'
    | '/hr-approval'
    | '/my-leave'
    | '/about'
    | '/guidelines'
    | '/test'
    | '/hr-approval/view-hr-approval-sheet'
    | '/reports/filed-leave'
    | '/for-approval/'
    | '/hr-approval/'
    | '/my-leave/'
    | '/my-leave/leave-form/{-$leaveId}'
    | '/my-leave/view-leave/$leaveId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/guidelines'
    | '/test'
    | '/hr-approval/view-hr-approval-sheet'
    | '/reports/filed-leave'
    | '/for-approval'
    | '/hr-approval'
    | '/my-leave'
    | '/my-leave/leave-form/{-$leaveId}'
    | '/my-leave/view-leave/$leaveId'
  id:
    | '__root__'
    | '/'
    | '/for-approval'
    | '/hr-approval'
    | '/my-leave'
    | '/about'
    | '/guidelines'
    | '/test'
    | '/hr-approval/view-hr-approval-sheet'
    | '/reports/filed-leave'
    | '/for-approval/'
    | '/hr-approval/'
    | '/my-leave/'
    | '/my-leave/leave-form/{-$leaveId}'
    | '/my-leave/view-leave/$leaveId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ForApprovalRouteRoute: typeof ForApprovalRouteRouteWithChildren
  HrApprovalRouteRoute: typeof HrApprovalRouteRouteWithChildren
  MyLeaveRouteRoute: typeof MyLeaveRouteRouteWithChildren
  AboutRoute: typeof AboutRoute
  GuidelinesRoute: typeof GuidelinesRoute
  TestRoute: typeof TestRoute
  ReportsFiledLeaveRoute: typeof ReportsFiledLeaveRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/test': {
      id: '/test'
      path: '/test'
      fullPath: '/test'
      preLoaderRoute: typeof TestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guidelines': {
      id: '/guidelines'
      path: '/guidelines'
      fullPath: '/guidelines'
      preLoaderRoute: typeof GuidelinesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/my-leave': {
      id: '/my-leave'
      path: '/my-leave'
      fullPath: '/my-leave'
      preLoaderRoute: typeof MyLeaveRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hr-approval': {
      id: '/hr-approval'
      path: '/hr-approval'
      fullPath: '/hr-approval'
      preLoaderRoute: typeof HrApprovalRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/for-approval': {
      id: '/for-approval'
      path: '/for-approval'
      fullPath: '/for-approval'
      preLoaderRoute: typeof ForApprovalRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/my-leave/': {
      id: '/my-leave/'
      path: '/'
      fullPath: '/my-leave/'
      preLoaderRoute: typeof MyLeaveIndexRouteImport
      parentRoute: typeof MyLeaveRouteRoute
    }
    '/hr-approval/': {
      id: '/hr-approval/'
      path: '/'
      fullPath: '/hr-approval/'
      preLoaderRoute: typeof HrApprovalIndexRouteImport
      parentRoute: typeof HrApprovalRouteRoute
    }
    '/for-approval/': {
      id: '/for-approval/'
      path: '/'
      fullPath: '/for-approval/'
      preLoaderRoute: typeof ForApprovalIndexRouteImport
      parentRoute: typeof ForApprovalRouteRoute
    }
    '/reports/filed-leave': {
      id: '/reports/filed-leave'
      path: '/reports/filed-leave'
      fullPath: '/reports/filed-leave'
      preLoaderRoute: typeof ReportsFiledLeaveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hr-approval/view-hr-approval-sheet': {
      id: '/hr-approval/view-hr-approval-sheet'
      path: '/view-hr-approval-sheet'
      fullPath: '/hr-approval/view-hr-approval-sheet'
      preLoaderRoute: typeof HrApprovalViewHrApprovalSheetRouteImport
      parentRoute: typeof HrApprovalRouteRoute
    }
    '/my-leave/view-leave/$leaveId': {
      id: '/my-leave/view-leave/$leaveId'
      path: '/view-leave/$leaveId'
      fullPath: '/my-leave/view-leave/$leaveId'
      preLoaderRoute: typeof MyLeaveViewLeaveLeaveIdRouteImport
      parentRoute: typeof MyLeaveRouteRoute
    }
    '/my-leave/leave-form/{-$leaveId}': {
      id: '/my-leave/leave-form/{-$leaveId}'
      path: '/leave-form/{-$leaveId}'
      fullPath: '/my-leave/leave-form/{-$leaveId}'
      preLoaderRoute: typeof MyLeaveLeaveFormChar123LeaveIdChar125RouteImport
      parentRoute: typeof MyLeaveRouteRoute
    }
  }
}

interface ForApprovalRouteRouteChildren {
  ForApprovalIndexRoute: typeof ForApprovalIndexRoute
}

const ForApprovalRouteRouteChildren: ForApprovalRouteRouteChildren = {
  ForApprovalIndexRoute: ForApprovalIndexRoute,
}

const ForApprovalRouteRouteWithChildren =
  ForApprovalRouteRoute._addFileChildren(ForApprovalRouteRouteChildren)

interface HrApprovalRouteRouteChildren {
  HrApprovalViewHrApprovalSheetRoute: typeof HrApprovalViewHrApprovalSheetRoute
  HrApprovalIndexRoute: typeof HrApprovalIndexRoute
}

const HrApprovalRouteRouteChildren: HrApprovalRouteRouteChildren = {
  HrApprovalViewHrApprovalSheetRoute: HrApprovalViewHrApprovalSheetRoute,
  HrApprovalIndexRoute: HrApprovalIndexRoute,
}

const HrApprovalRouteRouteWithChildren = HrApprovalRouteRoute._addFileChildren(
  HrApprovalRouteRouteChildren,
)

interface MyLeaveRouteRouteChildren {
  MyLeaveIndexRoute: typeof MyLeaveIndexRoute
  MyLeaveLeaveFormChar123LeaveIdChar125Route: typeof MyLeaveLeaveFormChar123LeaveIdChar125Route
  MyLeaveViewLeaveLeaveIdRoute: typeof MyLeaveViewLeaveLeaveIdRoute
}

const MyLeaveRouteRouteChildren: MyLeaveRouteRouteChildren = {
  MyLeaveIndexRoute: MyLeaveIndexRoute,
  MyLeaveLeaveFormChar123LeaveIdChar125Route:
    MyLeaveLeaveFormChar123LeaveIdChar125Route,
  MyLeaveViewLeaveLeaveIdRoute: MyLeaveViewLeaveLeaveIdRoute,
}

const MyLeaveRouteRouteWithChildren = MyLeaveRouteRoute._addFileChildren(
  MyLeaveRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ForApprovalRouteRoute: ForApprovalRouteRouteWithChildren,
  HrApprovalRouteRoute: HrApprovalRouteRouteWithChildren,
  MyLeaveRouteRoute: MyLeaveRouteRouteWithChildren,
  AboutRoute: AboutRoute,
  GuidelinesRoute: GuidelinesRoute,
  TestRoute: TestRoute,
  ReportsFiledLeaveRoute: ReportsFiledLeaveRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
