/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TestRouteImport } from './routes/test'
import { Route as GuidelinesRouteImport } from './routes/guidelines'
import { Route as AboutRouteImport } from './routes/about'
import { Route as MyLeaveRouteRouteImport } from './routes/my-leave/route'
import { Route as HrApprovalRouteRouteImport } from './routes/hr-approval/route'
import { Route as ForApprovalRouteRouteImport } from './routes/for-approval/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as MyLeaveIndexRouteImport } from './routes/my-leave/index'
import { Route as HrApprovalIndexRouteImport } from './routes/hr-approval/index'
import { Route as ForApprovalIndexRouteImport } from './routes/for-approval/index'
import { Route as ReportsFiledLeaveRouteImport } from './routes/reports/filed-leave'
import { Route as MyLeaveViewLeaveRouteImport } from './routes/my-leave/view-leave'
import { Route as HrApprovalViewHrApprovalFormRouteImport } from './routes/hr-approval/view-hr-approval-form'
import { Route as HrApprovalHrApprovalFormRouteImport } from './routes/hr-approval/hr-approval-form'
import { Route as ForApprovalViewForApprovalRouteImport } from './routes/for-approval/view-for-approval'
import { Route as MyLeaveLeaveFormChar123LeaveIdChar125RouteImport } from './routes/my-leave/leave-form.{-$leaveId}'

const TestRoute = TestRouteImport.update({
  id: '/test',
  path: '/test',
  getParentRoute: () => rootRouteImport,
} as any)
const GuidelinesRoute = GuidelinesRouteImport.update({
  id: '/guidelines',
  path: '/guidelines',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const MyLeaveRouteRoute = MyLeaveRouteRouteImport.update({
  id: '/my-leave',
  path: '/my-leave',
  getParentRoute: () => rootRouteImport,
} as any)
const HrApprovalRouteRoute = HrApprovalRouteRouteImport.update({
  id: '/hr-approval',
  path: '/hr-approval',
  getParentRoute: () => rootRouteImport,
} as any)
const ForApprovalRouteRoute = ForApprovalRouteRouteImport.update({
  id: '/for-approval',
  path: '/for-approval',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const MyLeaveIndexRoute = MyLeaveIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => MyLeaveRouteRoute,
} as any)
const HrApprovalIndexRoute = HrApprovalIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => HrApprovalRouteRoute,
} as any)
const ForApprovalIndexRoute = ForApprovalIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ForApprovalRouteRoute,
} as any)
const ReportsFiledLeaveRoute = ReportsFiledLeaveRouteImport.update({
  id: '/reports/filed-leave',
  path: '/reports/filed-leave',
  getParentRoute: () => rootRouteImport,
} as any)
const MyLeaveViewLeaveRoute = MyLeaveViewLeaveRouteImport.update({
  id: '/view-leave',
  path: '/view-leave',
  getParentRoute: () => MyLeaveRouteRoute,
} as any)
const HrApprovalViewHrApprovalFormRoute =
  HrApprovalViewHrApprovalFormRouteImport.update({
    id: '/view-hr-approval-form',
    path: '/view-hr-approval-form',
    getParentRoute: () => HrApprovalRouteRoute,
  } as any)
const HrApprovalHrApprovalFormRoute =
  HrApprovalHrApprovalFormRouteImport.update({
    id: '/hr-approval-form',
    path: '/hr-approval-form',
    getParentRoute: () => HrApprovalRouteRoute,
  } as any)
const ForApprovalViewForApprovalRoute =
  ForApprovalViewForApprovalRouteImport.update({
    id: '/view-for-approval',
    path: '/view-for-approval',
    getParentRoute: () => ForApprovalRouteRoute,
  } as any)
const MyLeaveLeaveFormChar123LeaveIdChar125Route =
  MyLeaveLeaveFormChar123LeaveIdChar125RouteImport.update({
    id: '/leave-form/{-$leaveId}',
    path: '/leave-form/{-$leaveId}',
    getParentRoute: () => MyLeaveRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/for-approval': typeof ForApprovalRouteRouteWithChildren
  '/hr-approval': typeof HrApprovalRouteRouteWithChildren
  '/my-leave': typeof MyLeaveRouteRouteWithChildren
  '/about': typeof AboutRoute
  '/guidelines': typeof GuidelinesRoute
  '/test': typeof TestRoute
  '/for-approval/view-for-approval': typeof ForApprovalViewForApprovalRoute
  '/hr-approval/hr-approval-form': typeof HrApprovalHrApprovalFormRoute
  '/hr-approval/view-hr-approval-form': typeof HrApprovalViewHrApprovalFormRoute
  '/my-leave/view-leave': typeof MyLeaveViewLeaveRoute
  '/reports/filed-leave': typeof ReportsFiledLeaveRoute
  '/for-approval/': typeof ForApprovalIndexRoute
  '/hr-approval/': typeof HrApprovalIndexRoute
  '/my-leave/': typeof MyLeaveIndexRoute
  '/my-leave/leave-form/{-$leaveId}': typeof MyLeaveLeaveFormChar123LeaveIdChar125Route
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/guidelines': typeof GuidelinesRoute
  '/test': typeof TestRoute
  '/for-approval/view-for-approval': typeof ForApprovalViewForApprovalRoute
  '/hr-approval/hr-approval-form': typeof HrApprovalHrApprovalFormRoute
  '/hr-approval/view-hr-approval-form': typeof HrApprovalViewHrApprovalFormRoute
  '/my-leave/view-leave': typeof MyLeaveViewLeaveRoute
  '/reports/filed-leave': typeof ReportsFiledLeaveRoute
  '/for-approval': typeof ForApprovalIndexRoute
  '/hr-approval': typeof HrApprovalIndexRoute
  '/my-leave': typeof MyLeaveIndexRoute
  '/my-leave/leave-form/{-$leaveId}': typeof MyLeaveLeaveFormChar123LeaveIdChar125Route
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/for-approval': typeof ForApprovalRouteRouteWithChildren
  '/hr-approval': typeof HrApprovalRouteRouteWithChildren
  '/my-leave': typeof MyLeaveRouteRouteWithChildren
  '/about': typeof AboutRoute
  '/guidelines': typeof GuidelinesRoute
  '/test': typeof TestRoute
  '/for-approval/view-for-approval': typeof ForApprovalViewForApprovalRoute
  '/hr-approval/hr-approval-form': typeof HrApprovalHrApprovalFormRoute
  '/hr-approval/view-hr-approval-form': typeof HrApprovalViewHrApprovalFormRoute
  '/my-leave/view-leave': typeof MyLeaveViewLeaveRoute
  '/reports/filed-leave': typeof ReportsFiledLeaveRoute
  '/for-approval/': typeof ForApprovalIndexRoute
  '/hr-approval/': typeof HrApprovalIndexRoute
  '/my-leave/': typeof MyLeaveIndexRoute
  '/my-leave/leave-form/{-$leaveId}': typeof MyLeaveLeaveFormChar123LeaveIdChar125Route
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/for-approval'
    | '/hr-approval'
    | '/my-leave'
    | '/about'
    | '/guidelines'
    | '/test'
    | '/for-approval/view-for-approval'
    | '/hr-approval/hr-approval-form'
    | '/hr-approval/view-hr-approval-form'
    | '/my-leave/view-leave'
    | '/reports/filed-leave'
    | '/for-approval/'
    | '/hr-approval/'
    | '/my-leave/'
    | '/my-leave/leave-form/{-$leaveId}'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/guidelines'
    | '/test'
    | '/for-approval/view-for-approval'
    | '/hr-approval/hr-approval-form'
    | '/hr-approval/view-hr-approval-form'
    | '/my-leave/view-leave'
    | '/reports/filed-leave'
    | '/for-approval'
    | '/hr-approval'
    | '/my-leave'
    | '/my-leave/leave-form/{-$leaveId}'
  id:
    | '__root__'
    | '/'
    | '/for-approval'
    | '/hr-approval'
    | '/my-leave'
    | '/about'
    | '/guidelines'
    | '/test'
    | '/for-approval/view-for-approval'
    | '/hr-approval/hr-approval-form'
    | '/hr-approval/view-hr-approval-form'
    | '/my-leave/view-leave'
    | '/reports/filed-leave'
    | '/for-approval/'
    | '/hr-approval/'
    | '/my-leave/'
    | '/my-leave/leave-form/{-$leaveId}'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ForApprovalRouteRoute: typeof ForApprovalRouteRouteWithChildren
  HrApprovalRouteRoute: typeof HrApprovalRouteRouteWithChildren
  MyLeaveRouteRoute: typeof MyLeaveRouteRouteWithChildren
  AboutRoute: typeof AboutRoute
  GuidelinesRoute: typeof GuidelinesRoute
  TestRoute: typeof TestRoute
  ReportsFiledLeaveRoute: typeof ReportsFiledLeaveRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/test': {
      id: '/test'
      path: '/test'
      fullPath: '/test'
      preLoaderRoute: typeof TestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guidelines': {
      id: '/guidelines'
      path: '/guidelines'
      fullPath: '/guidelines'
      preLoaderRoute: typeof GuidelinesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/my-leave': {
      id: '/my-leave'
      path: '/my-leave'
      fullPath: '/my-leave'
      preLoaderRoute: typeof MyLeaveRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hr-approval': {
      id: '/hr-approval'
      path: '/hr-approval'
      fullPath: '/hr-approval'
      preLoaderRoute: typeof HrApprovalRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/for-approval': {
      id: '/for-approval'
      path: '/for-approval'
      fullPath: '/for-approval'
      preLoaderRoute: typeof ForApprovalRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/my-leave/': {
      id: '/my-leave/'
      path: '/'
      fullPath: '/my-leave/'
      preLoaderRoute: typeof MyLeaveIndexRouteImport
      parentRoute: typeof MyLeaveRouteRoute
    }
    '/hr-approval/': {
      id: '/hr-approval/'
      path: '/'
      fullPath: '/hr-approval/'
      preLoaderRoute: typeof HrApprovalIndexRouteImport
      parentRoute: typeof HrApprovalRouteRoute
    }
    '/for-approval/': {
      id: '/for-approval/'
      path: '/'
      fullPath: '/for-approval/'
      preLoaderRoute: typeof ForApprovalIndexRouteImport
      parentRoute: typeof ForApprovalRouteRoute
    }
    '/reports/filed-leave': {
      id: '/reports/filed-leave'
      path: '/reports/filed-leave'
      fullPath: '/reports/filed-leave'
      preLoaderRoute: typeof ReportsFiledLeaveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/my-leave/view-leave': {
      id: '/my-leave/view-leave'
      path: '/view-leave'
      fullPath: '/my-leave/view-leave'
      preLoaderRoute: typeof MyLeaveViewLeaveRouteImport
      parentRoute: typeof MyLeaveRouteRoute
    }
    '/hr-approval/view-hr-approval-form': {
      id: '/hr-approval/view-hr-approval-form'
      path: '/view-hr-approval-form'
      fullPath: '/hr-approval/view-hr-approval-form'
      preLoaderRoute: typeof HrApprovalViewHrApprovalFormRouteImport
      parentRoute: typeof HrApprovalRouteRoute
    }
    '/hr-approval/hr-approval-form': {
      id: '/hr-approval/hr-approval-form'
      path: '/hr-approval-form'
      fullPath: '/hr-approval/hr-approval-form'
      preLoaderRoute: typeof HrApprovalHrApprovalFormRouteImport
      parentRoute: typeof HrApprovalRouteRoute
    }
    '/for-approval/view-for-approval': {
      id: '/for-approval/view-for-approval'
      path: '/view-for-approval'
      fullPath: '/for-approval/view-for-approval'
      preLoaderRoute: typeof ForApprovalViewForApprovalRouteImport
      parentRoute: typeof ForApprovalRouteRoute
    }
    '/my-leave/leave-form/{-$leaveId}': {
      id: '/my-leave/leave-form/{-$leaveId}'
      path: '/leave-form/{-$leaveId}'
      fullPath: '/my-leave/leave-form/{-$leaveId}'
      preLoaderRoute: typeof MyLeaveLeaveFormChar123LeaveIdChar125RouteImport
      parentRoute: typeof MyLeaveRouteRoute
    }
  }
}

interface ForApprovalRouteRouteChildren {
  ForApprovalViewForApprovalRoute: typeof ForApprovalViewForApprovalRoute
  ForApprovalIndexRoute: typeof ForApprovalIndexRoute
}

const ForApprovalRouteRouteChildren: ForApprovalRouteRouteChildren = {
  ForApprovalViewForApprovalRoute: ForApprovalViewForApprovalRoute,
  ForApprovalIndexRoute: ForApprovalIndexRoute,
}

const ForApprovalRouteRouteWithChildren =
  ForApprovalRouteRoute._addFileChildren(ForApprovalRouteRouteChildren)

interface HrApprovalRouteRouteChildren {
  HrApprovalHrApprovalFormRoute: typeof HrApprovalHrApprovalFormRoute
  HrApprovalViewHrApprovalFormRoute: typeof HrApprovalViewHrApprovalFormRoute
  HrApprovalIndexRoute: typeof HrApprovalIndexRoute
}

const HrApprovalRouteRouteChildren: HrApprovalRouteRouteChildren = {
  HrApprovalHrApprovalFormRoute: HrApprovalHrApprovalFormRoute,
  HrApprovalViewHrApprovalFormRoute: HrApprovalViewHrApprovalFormRoute,
  HrApprovalIndexRoute: HrApprovalIndexRoute,
}

const HrApprovalRouteRouteWithChildren = HrApprovalRouteRoute._addFileChildren(
  HrApprovalRouteRouteChildren,
)

interface MyLeaveRouteRouteChildren {
  MyLeaveViewLeaveRoute: typeof MyLeaveViewLeaveRoute
  MyLeaveIndexRoute: typeof MyLeaveIndexRoute
  MyLeaveLeaveFormChar123LeaveIdChar125Route: typeof MyLeaveLeaveFormChar123LeaveIdChar125Route
}

const MyLeaveRouteRouteChildren: MyLeaveRouteRouteChildren = {
  MyLeaveViewLeaveRoute: MyLeaveViewLeaveRoute,
  MyLeaveIndexRoute: MyLeaveIndexRoute,
  MyLeaveLeaveFormChar123LeaveIdChar125Route:
    MyLeaveLeaveFormChar123LeaveIdChar125Route,
}

const MyLeaveRouteRouteWithChildren = MyLeaveRouteRoute._addFileChildren(
  MyLeaveRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ForApprovalRouteRoute: ForApprovalRouteRouteWithChildren,
  HrApprovalRouteRoute: HrApprovalRouteRouteWithChildren,
  MyLeaveRouteRoute: MyLeaveRouteRouteWithChildren,
  AboutRoute: AboutRoute,
  GuidelinesRoute: GuidelinesRoute,
  TestRoute: TestRoute,
  ReportsFiledLeaveRoute: ReportsFiledLeaveRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
