/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ReportsRouteImport } from './routes/reports'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TicketsIndexRouteImport } from './routes/tickets/index'
import { Route as ManageIndexRouteImport } from './routes/manage/index'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as TicketsNewRouteImport } from './routes/tickets/new'
import { Route as TicketsTicketNumberRouteImport } from './routes/tickets/$ticketNumber'
import { Route as ManageTemplatesRouteImport } from './routes/manage/templates'
import { Route as ManageStaffRouteImport } from './routes/manage/staff'
import { Route as ManageCustomersRouteImport } from './routes/manage/customers'
import { Route as ManageCategoriesRouteImport } from './routes/manage/categories'
import { Route as ManageAdminsRouteImport } from './routes/manage/admins'
import { Route as AdminBoardsNewRouteImport } from './routes/admin/boards/new'
import { Route as AdminBoardsBoardIdRouteImport } from './routes/admin/boards/$boardId'

const ReportsRoute = ReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TicketsIndexRoute = TicketsIndexRouteImport.update({
  id: '/tickets/',
  path: '/tickets/',
  getParentRoute: () => rootRouteImport,
} as any)
const ManageIndexRoute = ManageIndexRouteImport.update({
  id: '/manage/',
  path: '/manage/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const TicketsNewRoute = TicketsNewRouteImport.update({
  id: '/tickets/new',
  path: '/tickets/new',
  getParentRoute: () => rootRouteImport,
} as any)
const TicketsTicketNumberRoute = TicketsTicketNumberRouteImport.update({
  id: '/tickets/$ticketNumber',
  path: '/tickets/$ticketNumber',
  getParentRoute: () => rootRouteImport,
} as any)
const ManageTemplatesRoute = ManageTemplatesRouteImport.update({
  id: '/manage/templates',
  path: '/manage/templates',
  getParentRoute: () => rootRouteImport,
} as any)
const ManageStaffRoute = ManageStaffRouteImport.update({
  id: '/manage/staff',
  path: '/manage/staff',
  getParentRoute: () => rootRouteImport,
} as any)
const ManageCustomersRoute = ManageCustomersRouteImport.update({
  id: '/manage/customers',
  path: '/manage/customers',
  getParentRoute: () => rootRouteImport,
} as any)
const ManageCategoriesRoute = ManageCategoriesRouteImport.update({
  id: '/manage/categories',
  path: '/manage/categories',
  getParentRoute: () => rootRouteImport,
} as any)
const ManageAdminsRoute = ManageAdminsRouteImport.update({
  id: '/manage/admins',
  path: '/manage/admins',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminBoardsNewRoute = AdminBoardsNewRouteImport.update({
  id: '/admin/boards/new',
  path: '/admin/boards/new',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminBoardsBoardIdRoute = AdminBoardsBoardIdRouteImport.update({
  id: '/admin/boards/$boardId',
  path: '/admin/boards/$boardId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/reports': typeof ReportsRoute
  '/manage/admins': typeof ManageAdminsRoute
  '/manage/categories': typeof ManageCategoriesRoute
  '/manage/customers': typeof ManageCustomersRoute
  '/manage/staff': typeof ManageStaffRoute
  '/manage/templates': typeof ManageTemplatesRoute
  '/tickets/$ticketNumber': typeof TicketsTicketNumberRoute
  '/tickets/new': typeof TicketsNewRoute
  '/admin/': typeof AdminIndexRoute
  '/manage/': typeof ManageIndexRoute
  '/tickets/': typeof TicketsIndexRoute
  '/admin/boards/$boardId': typeof AdminBoardsBoardIdRoute
  '/admin/boards/new': typeof AdminBoardsNewRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/reports': typeof ReportsRoute
  '/manage/admins': typeof ManageAdminsRoute
  '/manage/categories': typeof ManageCategoriesRoute
  '/manage/customers': typeof ManageCustomersRoute
  '/manage/staff': typeof ManageStaffRoute
  '/manage/templates': typeof ManageTemplatesRoute
  '/tickets/$ticketNumber': typeof TicketsTicketNumberRoute
  '/tickets/new': typeof TicketsNewRoute
  '/admin': typeof AdminIndexRoute
  '/manage': typeof ManageIndexRoute
  '/tickets': typeof TicketsIndexRoute
  '/admin/boards/$boardId': typeof AdminBoardsBoardIdRoute
  '/admin/boards/new': typeof AdminBoardsNewRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/reports': typeof ReportsRoute
  '/manage/admins': typeof ManageAdminsRoute
  '/manage/categories': typeof ManageCategoriesRoute
  '/manage/customers': typeof ManageCustomersRoute
  '/manage/staff': typeof ManageStaffRoute
  '/manage/templates': typeof ManageTemplatesRoute
  '/tickets/$ticketNumber': typeof TicketsTicketNumberRoute
  '/tickets/new': typeof TicketsNewRoute
  '/admin/': typeof AdminIndexRoute
  '/manage/': typeof ManageIndexRoute
  '/tickets/': typeof TicketsIndexRoute
  '/admin/boards/$boardId': typeof AdminBoardsBoardIdRoute
  '/admin/boards/new': typeof AdminBoardsNewRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/reports'
    | '/manage/admins'
    | '/manage/categories'
    | '/manage/customers'
    | '/manage/staff'
    | '/manage/templates'
    | '/tickets/$ticketNumber'
    | '/tickets/new'
    | '/admin/'
    | '/manage/'
    | '/tickets/'
    | '/admin/boards/$boardId'
    | '/admin/boards/new'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/reports'
    | '/manage/admins'
    | '/manage/categories'
    | '/manage/customers'
    | '/manage/staff'
    | '/manage/templates'
    | '/tickets/$ticketNumber'
    | '/tickets/new'
    | '/admin'
    | '/manage'
    | '/tickets'
    | '/admin/boards/$boardId'
    | '/admin/boards/new'
  id:
    | '__root__'
    | '/'
    | '/reports'
    | '/manage/admins'
    | '/manage/categories'
    | '/manage/customers'
    | '/manage/staff'
    | '/manage/templates'
    | '/tickets/$ticketNumber'
    | '/tickets/new'
    | '/admin/'
    | '/manage/'
    | '/tickets/'
    | '/admin/boards/$boardId'
    | '/admin/boards/new'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ReportsRoute: typeof ReportsRoute
  ManageAdminsRoute: typeof ManageAdminsRoute
  ManageCategoriesRoute: typeof ManageCategoriesRoute
  ManageCustomersRoute: typeof ManageCustomersRoute
  ManageStaffRoute: typeof ManageStaffRoute
  ManageTemplatesRoute: typeof ManageTemplatesRoute
  TicketsTicketNumberRoute: typeof TicketsTicketNumberRoute
  TicketsNewRoute: typeof TicketsNewRoute
  AdminIndexRoute: typeof AdminIndexRoute
  ManageIndexRoute: typeof ManageIndexRoute
  TicketsIndexRoute: typeof TicketsIndexRoute
  AdminBoardsBoardIdRoute: typeof AdminBoardsBoardIdRoute
  AdminBoardsNewRoute: typeof AdminBoardsNewRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/reports': {
      id: '/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof ReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tickets/': {
      id: '/tickets/'
      path: '/tickets'
      fullPath: '/tickets/'
      preLoaderRoute: typeof TicketsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/manage/': {
      id: '/manage/'
      path: '/manage'
      fullPath: '/manage/'
      preLoaderRoute: typeof ManageIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tickets/new': {
      id: '/tickets/new'
      path: '/tickets/new'
      fullPath: '/tickets/new'
      preLoaderRoute: typeof TicketsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tickets/$ticketNumber': {
      id: '/tickets/$ticketNumber'
      path: '/tickets/$ticketNumber'
      fullPath: '/tickets/$ticketNumber'
      preLoaderRoute: typeof TicketsTicketNumberRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/manage/templates': {
      id: '/manage/templates'
      path: '/manage/templates'
      fullPath: '/manage/templates'
      preLoaderRoute: typeof ManageTemplatesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/manage/staff': {
      id: '/manage/staff'
      path: '/manage/staff'
      fullPath: '/manage/staff'
      preLoaderRoute: typeof ManageStaffRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/manage/customers': {
      id: '/manage/customers'
      path: '/manage/customers'
      fullPath: '/manage/customers'
      preLoaderRoute: typeof ManageCustomersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/manage/categories': {
      id: '/manage/categories'
      path: '/manage/categories'
      fullPath: '/manage/categories'
      preLoaderRoute: typeof ManageCategoriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/manage/admins': {
      id: '/manage/admins'
      path: '/manage/admins'
      fullPath: '/manage/admins'
      preLoaderRoute: typeof ManageAdminsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/boards/new': {
      id: '/admin/boards/new'
      path: '/admin/boards/new'
      fullPath: '/admin/boards/new'
      preLoaderRoute: typeof AdminBoardsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/boards/$boardId': {
      id: '/admin/boards/$boardId'
      path: '/admin/boards/$boardId'
      fullPath: '/admin/boards/$boardId'
      preLoaderRoute: typeof AdminBoardsBoardIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ReportsRoute: ReportsRoute,
  ManageAdminsRoute: ManageAdminsRoute,
  ManageCategoriesRoute: ManageCategoriesRoute,
  ManageCustomersRoute: ManageCustomersRoute,
  ManageStaffRoute: ManageStaffRoute,
  ManageTemplatesRoute: ManageTemplatesRoute,
  TicketsTicketNumberRoute: TicketsTicketNumberRoute,
  TicketsNewRoute: TicketsNewRoute,
  AdminIndexRoute: AdminIndexRoute,
  ManageIndexRoute: ManageIndexRoute,
  TicketsIndexRoute: TicketsIndexRoute,
  AdminBoardsBoardIdRoute: AdminBoardsBoardIdRoute,
  AdminBoardsNewRoute: AdminBoardsNewRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
